# -*- coding: utf-8 -*-
"""DSVPROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-tsaAe4wD9jmLDmmkqYpEVmMO6eTa-J
"""

!pip install dash plotly

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from scipy import stats
import dash
from dash import dcc, html, Input, Output

# Checking sheet availability
excel_file = "Confectionary [4564].xlsx"
sheets = pd.ExcelFile(excel_file).sheet_names
print("Sheets available:", sheets)

df = pd.read_excel(excel_file, sheet_name=sheets[0])
print(df.head())

for col in df.columns:
    print(f"Unique values in {col}:")
    print(df[col].unique(), "\n")

# 4. Distribution & Skewness
cols = ['Units Sold', 'Cost(£)', 'Profit(£)', 'Revenue(£)']

# 1. Calculate and print skewness for all columns simultaneously
print("Skewness values:\n", df[cols].skew())

# 2. Plot all histograms in one command (no loop required)
df[cols].hist(figsize=(12, 8), bins=20, edgecolor='black', grid=False)
plt.suptitle("Distribution Overview")
plt.show()

# 6. Total revenue by Country & Confectionary
import pandas as pd
# Group, sum, and reset index in one line
summary = df.groupby(['Country(UK)', 'Confectionary'])['Revenue(£)'].sum().reset_index()
print(summary)

# 7. Grouped bar chart (Units Sold)
px.bar(df, x="Country(UK)", y="Units Sold", color="Confectionary", barmode="group",
       title="Units Sold by Country and Confectionary").show()

df["Profit Margin"] = df.apply(
    lambda row: row["Profit(£)"] / row["Revenue(£)"] if row["Revenue(£)"] > 0 else None,
    axis=1
)
margin_summary = df.groupby(['Country(UK)', 'Confectionary'])['Profit Margin'].mean().reset_index()
print(margin_summary)

fig = px.scatter(
    margin_summary,
    x="Country(UK)",
    y="Profit Margin",
    size="Profit Margin",
    color="Confectionary",
    hover_name="Confectionary",
    title="Bubble Chart of Profit Margin"
)
fig.show()

# Highest and lowest margins already computed
highest_margin = margin_summary.loc[margin_summary.groupby('Country(UK)')['Profit Margin'].idxmax()]
lowest_margin = margin_summary.loc[margin_summary.groupby('Country(UK)')['Profit Margin'].idxmin()]

# Merge for plotting
margin_compare = highest_margin[['Country(UK)', 'Profit Margin']].merge(
    lowest_margin[['Country(UK)', 'Profit Margin']],
    on='Country(UK)',
    suffixes=('_Highest', '_Lowest')
)

# Plot grouped bar chart using the concise Pandas plot wrapper
margin_compare.plot(
    x='Country(UK)',
    y=['Profit Margin_Highest', 'Profit Margin_Lowest'],
    kind='bar',
    figsize=(6, 4)
)

# Setting labels and aesthetics
plt.title("Highest vs Lowest Profit Margin per Country")
plt.ylabel("Profit Margin")
plt.xticks(rotation=0)
plt.legend(["Highest Margin", "Lowest Margin"])
plt.show()

# 9. Peak month per confectionary
df['Month'] = pd.to_datetime(df['Date']).dt.month

# 1. Group by Confectionary and Month, sum Units Sold, and reset the index
peak_months = df.groupby(['Confectionary', 'Month'])['Units Sold'].sum().reset_index()

# 2. Sort by Units Sold (descending) and keep only the first (highest) entry for each Confectionary
peak_months = peak_months.sort_values('Units Sold', ascending=False).drop_duplicates(subset='Confectionary')

print("Peak Month per Confectionary:\n", peak_months)

fig = px.bar(df, x="Month", y="Units Sold", color="Country(UK)", facet_col="Confectionary", facet_col_wrap=3, title="Monthly Sales by Confectionary & Country")

# Rotate facet labels
for annotation in fig.layout.annotations:
    annotation.textangle = 0

# Apply updates and show the figure in a single chained call
fig.update_layout(height=600, width=900, margin=dict(t=100), font=dict(size=12),
    updatemenus=[{"buttons": [
        {"method": "update", "label": "All Countries", "args": [{"visible": [True]*len(fig.data)}]},
        {"method": "update", "label": "England", "args": [{"visible": [trace.name == "England" for trace in fig.data]}]},
        {"method": "update", "label": "Scotland", "args": [{"visible": [trace.name == "Scotland" for trace in fig.data]}]},
        {"method": "update", "label": "Wales", "args": [{"visible": [trace.name == "Wales" for trace in fig.data]}]},
        {"method": "update", "label": "N. Ireland", "args": [{"visible": [trace.name == " N. Ireland" for trace in fig.data]}]},
        {"method": "update", "label": "Jersey", "args": [{"visible": [trace.name == "Jersey" for trace in fig.data]}]},
    ], "direction": "down", "x": 1.5, "y": 1.15, "showactive": True}]
).show()

# 11. Dashboard KPIs
total_revenue = df['Revenue(£)'].sum()
total_profit = df['Profit(£)'].sum()
avg_margin = df['Profit Margin'].mean()
peak_month_overall = df.groupby('Month')['Units Sold'].sum().idxmax()

print(f"Total Revenue: £{total_revenue:,.2f}\nTotal Profit: £{total_profit:,.2f}\nAverage Profit Margin: {avg_margin:.2%}\nPeak Month Overall: {peak_month_overall}")

import pandas as pd
import plotly.express as px
import dash
from dash import dcc, html, Input, Output

# Load your dataset
# df = pd.read_csv("your_confectionary_data.csv")
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month
df["Profit Margin"] = df.apply(
    lambda row: row["Profit(£)"] / row["Revenue(£)"] if row["Revenue(£)"] > 0 else None,
    axis=1
)

# Initialize Dash app
app = dash.Dash(__name__)
server = app.server

# Layout
app.layout = html.Div([
    html.H1("British Confectionary Dashboard", style={'textAlign': 'center'}),

    html.Div([
        html.Div([
            html.Label("Select Region"),
            dcc.Dropdown(
                id='region-dropdown',
                options=[{'label': r, 'value': r} for r in sorted(df['Country(UK)'].unique())],
                value='England'
            )
        ], style={'width': '30%', 'display': 'inline-block'}),

        html.Div([
            html.Label("Select Year"),
            dcc.Dropdown(
                id='year-dropdown',
                options=[{'label': y, 'value': y} for y in sorted(df['Date'].dt.year.unique())],
                value=2020
            )
        ], style={'width': '30%', 'display': 'inline-block'}),

        html.Div([
            html.Label("Select Products"),
            dcc.Checklist(
                id='product-checklist',
                options=[{'label': p, 'value': p} for p in sorted(df['Confectionary'].unique())],
                value=sorted(df['Confectionary'].unique()),
                inline=True
            )
        ], style={'width': '100%', 'paddingTop': '10px'})
    ], style={'padding': '10px'}),

    html.Div(id='kpi-block', style={'padding': '20px'}),

    html.Div([
        dcc.Graph(id='revenue-chart'),
        dcc.Graph(id='margin-chart')
    ])
])

# Callback
@app.callback(
    [Output('kpi-block', 'children'),
     Output('revenue-chart', 'figure'),
     Output('margin-chart', 'figure')],
    [Input('region-dropdown', 'value'),
     Input('year-dropdown', 'value'),
     Input('product-checklist', 'value')]
)
def update_dashboard(region, year, products):
    filtered = df[
        (df['Country(UK)'] == region) &
        (df['Date'].dt.year == year) &
        (df['Confectionary'].isin(products))
    ]

    total_revenue = filtered['Revenue(£)'].sum()
    total_profit = filtered['Profit(£)'].sum()
    avg_margin = filtered['Profit Margin'].mean()
    units_sold = filtered['Units Sold'].sum()

    kpi_display = html.Div([
        html.H4(f"Total Revenue (£): £{total_revenue:,.0f}"),
        html.H4(f"Total Profit (£): £{total_profit:,.0f}"),
        html.H4(f"Average Margin (%): {avg_margin:.2%}"),
        html.H4(f"Units Sold: {units_sold:,}")
    ])

    revenue_fig = px.bar(
        filtered.groupby('Confectionary')['Revenue(£)'].sum().reset_index(),
        x='Confectionary',
        y='Revenue(£)',
        title=f"Revenue by Product ({region})"
    )

    margin_fig = px.bar(
        filtered.groupby('Confectionary')['Profit Margin'].mean().reset_index(),
        x='Confectionary',
        y='Profit Margin',
        title="Average Margin (%) by Product"
    )

    return kpi_display, revenue_fig, margin_fig

# Run app
if __name__ == '__main__':
    app.run(debug=True)

import pandas as pd
import plotly.express as px
import dash
from dash import dcc, html, Input, Output

# --- 1. Load your dataset (REPLACEMENT for commented-out line) ---
# Create a sample DataFrame 'df' for the code to run
data = {
    'Date': ['2020-01-01', '2020-01-01', '2020-02-01', '2021-01-01', '2021-02-01', '2021-01-01'],
    'Country(UK)': ['England', 'Scotland', 'England', 'Wales', 'England', 'Scotland'],
    'Confectionary': ['Choc Bar', 'Gummy', 'Choc Bar', 'Fudge', 'Gummy', 'Choc Bar'],
    'Revenue(£)': [1000, 500, 1500, 800, 200, 1200],
    'Profit(£)': [200, 50, 450, 160, 40, 300],
    'Units Sold': [100, 50, 150, 80, 20, 120]
}
df = pd.DataFrame(data)

# Data Preprocessing (Original Code)
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month
df["Profit Margin"] = df.apply(
    lambda row: row["Profit(£)"] / row["Revenue(£)"] if row["Revenue(£)"] > 0 else None,
    axis=1
)

# Initialize Dash app
app = dash.Dash(__name__)
server = app.server

# --- 2. Layout (Original Code) ---
app.layout = html.Div([
    html.H1("British Confectionary Dashboard", style={'textAlign': 'center'}),

    html.Div([
        html.Div([
            html.Label("Select Region"),
            dcc.Dropdown(
                id='region-dropdown',
                options=[{'label': r, 'value': r} for r in sorted(df['Country(UK)'].unique())],
                # Ensure the default value exists in the sample data
                value='England'
            )
        ], style={'width': '30%', 'display': 'inline-block', 'paddingRight': '15px'}),

        html.Div([
            html.Label("Select Year"),
            dcc.Dropdown(
                id='year-dropdown',
                options=[{'label': y, 'value': y} for y in sorted(df['Date'].dt.year.unique())],
                # Ensure the default value exists in the sample data
                value=2020
            )
        ], style={'width': '30%', 'display': 'inline-block', 'paddingRight': '15px'}),

        html.Div([
            html.Label("Select Products"),
            dcc.Checklist(
                id='product-checklist',
                options=[{'label': p, 'value': p} for p in sorted(df['Confectionary'].unique())],
                value=sorted(df['Confectionary'].unique()),
                inline=True
            )
        ], style={'width': '100%', 'paddingTop': '10px'})
    ], style={'padding': '10px', 'border': '1px solid #ccc', 'marginBottom': '20px'}),

    # KPI Block Styling
    html.Div(id='kpi-block', style={
        'padding': '20px',
        'backgroundColor': '#f9f9f9',
        'borderRadius': '5px',
        'display': 'flex',
        'justifyContent': 'space-around',
        'marginBottom': '20px'
    }),

    # Charts Layout
    html.Div([
        html.Div(dcc.Graph(id='revenue-chart'), style={'width': '50%', 'display': 'inline-block'}),
        html.Div(dcc.Graph(id='margin-chart'), style={'width': '50%', 'display': 'inline-block'})
    ])
])

# --- 3. Callback (Original Code) ---
@app.callback(
    [Output('kpi-block', 'children'),
     Output('revenue-chart', 'figure'),
     Output('margin-chart', 'figure')],
    [Input('region-dropdown', 'value'),
     Input('year-dropdown', 'value'),
     Input('product-checklist', 'value')]
)
def update_dashboard(region, year, products):
    # Ensure products is a list, even if only one is selected
    if not isinstance(products, list):
        products = [products]

    filtered = df[
        (df['Country(UK)'] == region) &
        (df['Date'].dt.year == year) &
        (df['Confectionary'].isin(products))
    ]

    # Handle case where filtered data is empty
    if filtered.empty:
        return (
            html.H4("No Data for Selected Filters.", style={'color': 'red'}),
            {}, # Empty figure for revenue
            {}  # Empty figure for margin
        )

    total_revenue = filtered['Revenue(£)'].sum()
    total_profit = filtered['Profit(£)'].sum()
    avg_margin = filtered['Profit Margin'].mean()
    units_sold = filtered['Units Sold'].sum()

    # KPI Display Structure (Improved for better presentation)
    kpi_display = [
        html.Div([
            html.H3(f"£{total_revenue:,.0f}", style={'color': '#007bff'}),
            html.P("Total Revenue (£)")
        ], style={'textAlign': 'center'}),
        html.Div([
            html.H3(f"£{total_profit:,.0f}", style={'color': '#28a745'}),
            html.P("Total Profit (£)")
        ], style={'textAlign': 'center'}),
        html.Div([
            html.H3(f"{avg_margin:.2%}", style={'color': '#ffc107'}),
            html.P("Average Margin (%)")
        ], style={'textAlign': 'center'}),
        html.Div([
            html.H3(f"{units_sold:,}", style={'color': '#dc3545'}),
            html.P("Units Sold")
        ], style={'textAlign': 'center'}),
    ]

    # Revenue Chart
    revenue_data = filtered.groupby('Confectionary')['Revenue(£)'].sum().reset_index()
    revenue_fig = px.bar(
        revenue_data,
        x='Confectionary',
        y='Revenue(£)',
        title=f"Revenue by Product ({region}, {year})",
        color='Confectionary'
    )

    # Margin Chart
    margin_data = filtered.groupby('Confectionary')['Profit Margin'].mean().reset_index()
    margin_fig = px.bar(
        margin_data,
        x='Confectionary',
        y='Profit Margin',
        title=f"Average Margin (%) by Product ({year})",
        color='Confectionary'
    )
    # Format the y-axis as percentage
    margin_fig.update_layout(yaxis_tickformat='.1%')

    return kpi_display, revenue_fig, margin_fig

# Run app
if __name__ == '__main__':
    # You may need to run 'pip install dash pandas plotly' if dependencies are missing.
    print("🚀 Running Dash App. Open http://127.0.0.1:8050/ in your browser.")
    app.run(debug=True, host='0.0.0.0')

